apiVersion: v1
kind: Service
metadata:
  name: course-app-service
spec:
  type: NodePort
  selector:
    app: course-app
  ports:
    - port: 8080        # Cluster port
      targetPort: 8080  # Container port
      nodePort: 30080   # Host port
