name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # WSL self-hosted runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      # ✅ Build image with TWO tags
      - name: Build Docker image
        run: |
          docker build \
            -t prasadkadam125/course-app:${GITHUB_SHA::8} \
            -t prasadkadam125/course-app:latest .

      # ✅ Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ✅ Push BOTH tags
      - name: Push Docker image
        run: |
          docker push prasadkadam125/course-app:${GITHUB_SHA::8}
          docker push prasadkadam125/course-app:latest

      # ✅ Update deployment using immutable tag
      - name: Update Deployment in kind
        run: |
          kubectl set image deployment/course-app \
            course-app=prasadkadam125/course-app:${GITHUB_SHA::8}
          kubectl rollout status deployment/course-app --timeout=5m

